// Code generated by okapi-gen-typed. DO NOT EDIT.
//
// Source: file://./openapi.yaml

package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"mime"
	"net/http"
	"net/url"
	"strconv"
	"strings"
)

// Client is the typed HTTP client for the generated API.
type Client struct {
	// BaseURL is prepended to every request path (no trailing slash).
	BaseURL string
	// HTTP is the underlying HTTP client. nil falls back to http.DefaultClient.
	HTTP *http.Client
	// DefaultHeaders are merged onto every request before per-call headers.
	DefaultHeaders http.Header
}

// NewClient returns a Client targeting baseURL.
func NewClient(baseURL string) *Client {
	return &Client{BaseURL: strings.TrimRight(baseURL, "/")}
}

// APIResponse carries the HTTP metadata of a response — the exact
// status code (200 vs 201 vs 204, ...) and the response headers.
// Every generated method returns it just before the error, and it is
// non-nil whenever an HTTP response was received — including non-2xx
// responses (alongside the *APIError) and 2xx responses whose body
// failed to read or decode. It is nil only when no response arrived
// at all (request construction or transport errors).
type APIResponse struct {
	StatusCode int
	Header     http.Header
}

// APIError is returned for non-2xx responses. It captures the HTTP
// status, the response headers, the raw response body, and — for JSON
// error bodies — the decoded RFC 7807 problem details.
type APIError struct {
	StatusCode int
	Status     string
	Method     string
	URL        string
	Body       []byte
	// Problem holds the decoded RFC 7807 payload when the response
	// carried application/problem+json (or application/json) and the
	// body parsed as a JSON object. nil otherwise; Body always keeps
	// the raw bytes either way.
	Problem *APIProblem
	// Header holds the HTTP response headers, e.g. Retry-After on 429
	// responses.
	Header http.Header
}

func (e *APIError) Error() string {
	if len(e.Body) > 0 {
		return fmt.Sprintf("%s %s: %s: %s", e.Method, e.URL, e.Status, string(e.Body))
	}
	return fmt.Sprintf("%s %s: %s", e.Method, e.URL, e.Status)
}

// APIProblem is an RFC 7807 "problem details" object. Members beyond
// the five standard ones are preserved in Extensions as raw JSON.
type APIProblem struct {
	Type     string `json:"type,omitempty"`
	Title    string `json:"title,omitempty"`
	Status   int    `json:"status,omitempty"`
	Detail   string `json:"detail,omitempty"`
	Instance string `json:"instance,omitempty"`

	// Extensions holds any non-standard members (e.g. a per-field
	// "errors" array) keyed by member name.
	Extensions map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes the standard RFC 7807 members and captures
// everything else in Extensions.
func (p *APIProblem) UnmarshalJSON(data []byte) error {
	type plain APIProblem
	var std plain
	if err := json.Unmarshal(data, &std); err != nil {
		return err
	}
	var members map[string]json.RawMessage
	if err := json.Unmarshal(data, &members); err != nil {
		return err
	}
	for _, k := range []string{"type", "title", "status", "detail", "instance"} {
		delete(members, k)
	}
	if len(members) > 0 {
		std.Extensions = members
	}
	*p = APIProblem(std)
	return nil
}

// newAPIError builds the error for a non-2xx response, best-effort
// decoding an RFC 7807 problem body. A malformed problem body never
// masks the HTTP error: Body always carries the raw bytes.
func newAPIError(resp *http.Response, method, url string, body []byte) *APIError {
	apiErr := &APIError{
		StatusCode: resp.StatusCode,
		Status:     resp.Status,
		Method:     method,
		URL:        url,
		Body:       body,
		Header:     resp.Header,
	}
	mt, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
	if err == nil && (mt == "application/problem+json" || mt == "application/json") {
		var prob APIProblem
		if json.Unmarshal(body, &prob) == nil {
			apiErr.Problem = &prob
		}
	}
	return apiErr
}

// httpClient returns c.HTTP or http.DefaultClient.
func (c *Client) httpClient() *http.Client {
	if c.HTTP != nil {
		return c.HTTP
	}
	return http.DefaultClient
}

// send builds and issues one HTTP request and maps non-2xx responses
// to *APIError. The *APIResponse is non-nil whenever a response was
// received, even on error. On success the caller owns resp.Body. Its
// signature is what couples the generated methods to the manual
// transport plumbing — keep it stable.
func (c *Client) send(
	ctx context.Context,
	method, pathTemplate string,
	pathParams map[string]string,
	query url.Values,
	headers http.Header,
	body io.Reader,
	contentType, accept string,
) (*http.Response, *APIResponse, error) {
	path := pathTemplate
	for k, v := range pathParams {
		// OpenAPI path params are single-segment values, so we escape "/"
		// in addition to what url.PathEscape covers — otherwise an id
		// like "a/b" would route to a sibling segment.
		escaped := strings.ReplaceAll(url.PathEscape(v), "/", "%2F")
		path = strings.ReplaceAll(path, "{"+k+"}", escaped)
	}
	full := c.BaseURL + path
	if len(query) > 0 {
		full += "?" + query.Encode()
	}

	req, err := http.NewRequestWithContext(ctx, method, full, body)
	if err != nil {
		return nil, nil, err
	}
	for k, vv := range c.DefaultHeaders {
		for _, v := range vv {
			req.Header.Add(k, v)
		}
	}
	for k, vv := range headers {
		for _, v := range vv {
			req.Header.Set(k, v)
		}
	}
	if body != nil && req.Header.Get("Content-Type") == "" {
		req.Header.Set("Content-Type", contentType)
	}
	if req.Header.Get("Accept") == "" {
		req.Header.Set("Accept", accept)
	}

	resp, err := c.httpClient().Do(req)
	if err != nil {
		return nil, nil, err
	}
	meta := &APIResponse{StatusCode: resp.StatusCode, Header: resp.Header}

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		respBody, err := io.ReadAll(resp.Body)
		resp.Body.Close()
		if err != nil {
			return nil, meta, fmt.Errorf("read response: %w", err)
		}
		return nil, meta, newAPIError(resp, method, full, respBody)
	}
	return resp, meta, nil
}

// do issues a request and decodes the JSON response body into out
// (skipped when out is nil or the body is empty). The response
// metadata is returned so methods can surface the status code and
// declared headers; it stays non-nil on read and decode failures —
// the server did respond, and the caller can still see how.
func (c *Client) do(
	ctx context.Context,
	method, pathTemplate string,
	pathParams map[string]string,
	query url.Values,
	headers http.Header,
	body io.Reader,
	contentType, accept string,
	out any,
) (*APIResponse, error) {
	resp, meta, err := c.send(ctx, method, pathTemplate, pathParams, query, headers, body, contentType, accept)
	if err != nil {
		return meta, err
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return meta, fmt.Errorf("read response: %w", err)
	}
	if out == nil || len(respBody) == 0 {
		return meta, nil
	}
	if err := json.Unmarshal(respBody, out); err != nil {
		return meta, fmt.Errorf("decode response: %w", err)
	}
	return meta, nil
}

// doStream issues a request and hands the raw response body back to
// the caller, who must close it.
func (c *Client) doStream(
	ctx context.Context,
	method, pathTemplate string,
	pathParams map[string]string,
	query url.Values,
	headers http.Header,
	body io.Reader,
	contentType, accept string,
) (io.ReadCloser, *APIResponse, error) {
	resp, meta, err := c.send(ctx, method, pathTemplate, pathParams, query, headers, body, contentType, accept)
	if err != nil {
		return nil, meta, err
	}
	return resp.Body, meta, nil
}

// jsonBody marshals v into an in-memory reader for the request body.
// Generated methods with a JSON request body funnel through here so
// send can treat every body as a plain io.Reader.
func jsonBody(v any) (io.Reader, error) {
	buf, err := json.Marshal(v)
	if err != nil {
		return nil, fmt.Errorf("encode body: %w", err)
	}
	return bytes.NewReader(buf), nil
}

// formatPathValue renders a primitive into a path/query string. Enums
// are stringly typed in the generated code so this works for them too.
func formatPathValue(v any) string {
	switch x := v.(type) {
	case string:
		return x
	case int:
		return strconv.Itoa(x)
	case int32:
		return strconv.FormatInt(int64(x), 10)
	case int64:
		return strconv.FormatInt(x, 10)
	case bool:
		return strconv.FormatBool(x)
	case float32:
		return strconv.FormatFloat(float64(x), 'f', -1, 32)
	case float64:
		return strconv.FormatFloat(x, 'f', -1, 64)
	case fmt.Stringer:
		return x.String()
	default:
		return fmt.Sprint(v)
	}
}

// Create an item
func (c *Client) CreateItem(ctx context.Context, idempotencyKey string, body CreateItemBody) (*Item, *APIResponse, error) {
	pathParams := map[string]string{}
	query := url.Values{}
	headers := http.Header{}
	_ = pathParams
	_ = query
	_ = headers
	headers.Set("Idempotency-Key", formatPathValue(idempotencyKey))
	bodyReader, err := jsonBody(body)
	if err != nil {
		return nil, nil, err
	}
	var out Item
	apiResp, err := c.do(ctx, "POST", "/items", pathParams, query, headers, bodyReader, "application/json", "application/json", &out)
	if err != nil {
		return nil, apiResp, err
	}
	return &out, apiResp, nil
}

// Delete an item
func (c *Client) DeleteItem(ctx context.Context, id int64, idempotencyKey string, ifMatch string) (*APIResponse, error) {
	pathParams := map[string]string{}
	query := url.Values{}
	headers := http.Header{}
	_ = pathParams
	_ = query
	_ = headers
	pathParams["id"] = formatPathValue(id)
	headers.Set("Idempotency-Key", formatPathValue(idempotencyKey))
	headers.Set("If-Match", formatPathValue(ifMatch))
	apiResp, err := c.do(ctx, "DELETE", "/items/{id}", pathParams, query, headers, nil, "", "application/json", nil)
	if err != nil {
		return apiResp, err
	}
	return apiResp, nil
}

// Export items as CSV
//
// The returned io.ReadCloser streams the raw text/csv response body;
// the caller must close it.
func (c *Client) ExportItems(ctx context.Context) (io.ReadCloser, *APIResponse, error) {
	pathParams := map[string]string{}
	query := url.Values{}
	headers := http.Header{}
	_ = pathParams
	_ = query
	_ = headers
	respBody, apiResp, err := c.doStream(ctx, "GET", "/items/export", pathParams, query, headers, nil, "", "text/csv")
	if err != nil {
		return nil, apiResp, err
	}
	return respBody, apiResp, nil
}

// GetItemResponseHeaders carries the response headers declared on GetItem's
// success response. Headers absent from the response are left as zero
// values.
type GetItemResponseHeaders struct {
	CacheControl string
	// Entity tag for the returned item
	Etag string
}

// Get an item
func (c *Client) GetItem(ctx context.Context, id int64) (*Item, GetItemResponseHeaders, *APIResponse, error) {
	pathParams := map[string]string{}
	query := url.Values{}
	headers := http.Header{}
	_ = pathParams
	_ = query
	_ = headers
	pathParams["id"] = formatPathValue(id)
	var out Item
	apiResp, err := c.do(ctx, "GET", "/items/{id}", pathParams, query, headers, nil, "", "application/json", &out)
	if err != nil {
		return nil, GetItemResponseHeaders{}, apiResp, err
	}
	outHeaders := GetItemResponseHeaders{}
	outHeaders.CacheControl = apiResp.Header.Get("Cache-Control")
	outHeaders.Etag = apiResp.Header.Get("ETag")
	return &out, outHeaders, apiResp, nil
}

// Liveness check
func (c *Client) Healthz(ctx context.Context) (*Health, *APIResponse, error) {
	pathParams := map[string]string{}
	query := url.Values{}
	headers := http.Header{}
	_ = pathParams
	_ = query
	_ = headers
	var out Health
	apiResp, err := c.do(ctx, "GET", "/healthz", pathParams, query, headers, nil, "", "application/json", &out)
	if err != nil {
		return nil, apiResp, err
	}
	return &out, apiResp, nil
}

// Bulk-import items from a CSV upload
//
// The request body is streamed as application/octet-stream; it is not buffered.
func (c *Client) ImportItems(ctx context.Context, body io.Reader) (*APIResponse, error) {
	pathParams := map[string]string{}
	query := url.Values{}
	headers := http.Header{}
	_ = pathParams
	_ = query
	_ = headers
	apiResp, err := c.do(ctx, "POST", "/items/import", pathParams, query, headers, body, "application/octet-stream", "application/json", nil)
	if err != nil {
		return apiResp, err
	}
	return apiResp, nil
}

// List items
func (c *Client) ListItems(ctx context.Context, cursor *string, limit *int64) (*ItemList, *APIResponse, error) {
	pathParams := map[string]string{}
	query := url.Values{}
	headers := http.Header{}
	_ = pathParams
	_ = query
	_ = headers
	if cursor != nil {
		query.Set("cursor", formatPathValue(*cursor))
	}
	if limit != nil {
		query.Set("limit", formatPathValue(*limit))
	}
	var out ItemList
	apiResp, err := c.do(ctx, "GET", "/items", pathParams, query, headers, nil, "", "application/json", &out)
	if err != nil {
		return nil, apiResp, err
	}
	return &out, apiResp, nil
}
