// Code generated by okapi-gen-typed. DO NOT EDIT.
//
// Source: file://./examples/typed-client/openapi.yaml

package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strconv"
	"strings"
)

// Client is the typed HTTP client for the generated API.
type Client struct {
	// BaseURL is prepended to every request path (no trailing slash).
	BaseURL string
	// HTTP is the underlying HTTP client. nil falls back to http.DefaultClient.
	HTTP *http.Client
	// DefaultHeaders are merged onto every request before per-call headers.
	DefaultHeaders http.Header
}

// NewClient returns a Client targeting baseURL.
func NewClient(baseURL string) *Client {
	return &Client{BaseURL: strings.TrimRight(baseURL, "/")}
}

// APIError is returned for non-2xx responses. It captures the HTTP
// status, the raw response body, and any decoded JSON payload.
type APIError struct {
	StatusCode int
	Status     string
	Method     string
	URL        string
	Body       []byte
}

func (e *APIError) Error() string {
	if len(e.Body) > 0 {
		return fmt.Sprintf("%s %s: %s: %s", e.Method, e.URL, e.Status, string(e.Body))
	}
	return fmt.Sprintf("%s %s: %s", e.Method, e.URL, e.Status)
}

// httpClient returns c.HTTP or http.DefaultClient.
func (c *Client) httpClient() *http.Client {
	if c.HTTP != nil {
		return c.HTTP
	}
	return http.DefaultClient
}

// do is the shared transport for every typed method. Its signature is
// what couples the generated methods to the manual transport plumbing —
// keep it stable.
func (c *Client) do(
	ctx context.Context,
	method, pathTemplate string,
	pathParams map[string]string,
	query url.Values,
	headers http.Header,
	body any,
	out any,
) error {
	path := pathTemplate
	for k, v := range pathParams {
		// OpenAPI path params are single-segment values, so we escape "/"
		// in addition to what url.PathEscape covers — otherwise an id
		// like "a/b" would route to a sibling segment.
		escaped := strings.ReplaceAll(url.PathEscape(v), "/", "%2F")
		path = strings.ReplaceAll(path, "{"+k+"}", escaped)
	}
	full := c.BaseURL + path
	if len(query) > 0 {
		full += "?" + query.Encode()
	}

	var reader io.Reader
	if body != nil {
		buf, err := json.Marshal(body)
		if err != nil {
			return fmt.Errorf("encode body: %w", err)
		}
		reader = bytes.NewReader(buf)
	}

	req, err := http.NewRequestWithContext(ctx, method, full, reader)
	if err != nil {
		return err
	}
	for k, vv := range c.DefaultHeaders {
		for _, v := range vv {
			req.Header.Add(k, v)
		}
	}
	for k, vv := range headers {
		for _, v := range vv {
			req.Header.Set(k, v)
		}
	}
	if body != nil && req.Header.Get("Content-Type") == "" {
		req.Header.Set("Content-Type", "application/json")
	}
	if req.Header.Get("Accept") == "" {
		req.Header.Set("Accept", "application/json")
	}

	resp, err := c.httpClient().Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("read response: %w", err)
	}

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return &APIError{
			StatusCode: resp.StatusCode,
			Status:     resp.Status,
			Method:     method,
			URL:        full,
			Body:       respBody,
		}
	}

	if out == nil || len(respBody) == 0 {
		return nil
	}
	if err := json.Unmarshal(respBody, out); err != nil {
		return fmt.Errorf("decode response: %w", err)
	}
	return nil
}

// formatPathValue renders a primitive into a path/query string. Enums
// are stringly typed in the generated code so this works for them too.
func formatPathValue(v any) string {
	switch x := v.(type) {
	case string:
		return x
	case int:
		return strconv.Itoa(x)
	case int32:
		return strconv.FormatInt(int64(x), 10)
	case int64:
		return strconv.FormatInt(x, 10)
	case bool:
		return strconv.FormatBool(x)
	case float32:
		return strconv.FormatFloat(float64(x), 'f', -1, 32)
	case float64:
		return strconv.FormatFloat(x, 'f', -1, 64)
	case fmt.Stringer:
		return x.String()
	default:
		return fmt.Sprint(v)
	}
}

// CreateItemParams collects the inputs for CreateItem.
type CreateItemParams struct {
	IdempotencyKey string         `json:"-" header:"Idempotency-Key"`
	Body           CreateItemBody `json:"-"`
}

// Create an item
func (c *Client) CreateItem(ctx context.Context, params CreateItemParams) (*Item, error) {
	pathParams := map[string]string{}
	query := url.Values{}
	headers := http.Header{}
	_ = pathParams
	_ = query
	_ = headers
	headers.Set("Idempotency-Key", formatPathValue(params.IdempotencyKey))
	var out Item
	if err := c.do(ctx, "POST", "/items", pathParams, query, headers, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteItemParams collects the inputs for DeleteItem.
type DeleteItemParams struct {
	Id             int64  `json:"-" path:"id"`
	IdempotencyKey string `json:"-" header:"Idempotency-Key"`
	IfMatch        string `json:"-" header:"If-Match"`
}

// Delete an item
func (c *Client) DeleteItem(ctx context.Context, params DeleteItemParams) error {
	pathParams := map[string]string{}
	query := url.Values{}
	headers := http.Header{}
	_ = pathParams
	_ = query
	_ = headers
	pathParams["id"] = formatPathValue(params.Id)
	headers.Set("Idempotency-Key", formatPathValue(params.IdempotencyKey))
	headers.Set("If-Match", formatPathValue(params.IfMatch))
	if err := c.do(ctx, "DELETE", "/items/{id}", pathParams, query, headers, nil, nil); err != nil {
		return err
	}
	return nil
}

// GetItemParams collects the inputs for GetItem.
type GetItemParams struct {
	Id int64 `json:"-" path:"id"`
}

// Get an item
func (c *Client) GetItem(ctx context.Context, params GetItemParams) (*Item, error) {
	pathParams := map[string]string{}
	query := url.Values{}
	headers := http.Header{}
	_ = pathParams
	_ = query
	_ = headers
	pathParams["id"] = formatPathValue(params.Id)
	var out Item
	if err := c.do(ctx, "GET", "/items/{id}", pathParams, query, headers, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Liveness check
func (c *Client) Healthz(ctx context.Context) (*Health, error) {
	pathParams := map[string]string{}
	query := url.Values{}
	headers := http.Header{}
	_ = pathParams
	_ = query
	_ = headers
	var out Health
	if err := c.do(ctx, "GET", "/healthz", pathParams, query, headers, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListItemsParams collects the inputs for ListItems.
type ListItemsParams struct {
	Cursor *string `json:"-" query:"cursor"`
	Limit  *int64  `json:"-" query:"limit"`
}

// List items
func (c *Client) ListItems(ctx context.Context, params ListItemsParams) (*ItemList, error) {
	pathParams := map[string]string{}
	query := url.Values{}
	headers := http.Header{}
	_ = pathParams
	_ = query
	_ = headers
	if params.Limit != nil {
		query.Set("limit", formatPathValue(*params.Limit))
	}
	if params.Cursor != nil {
		query.Set("cursor", formatPathValue(*params.Cursor))
	}
	var out ItemList
	if err := c.do(ctx, "GET", "/items", pathParams, query, headers, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
