// Code generated by okapi-gen-typed. DO NOT EDIT.
//
// Source: file://./openapi.yaml

package client

type CreateItemBody struct {
	Name string `json:"name"`
}

type Health struct {
	Status string `json:"status"`
}

type Item struct {
	Id        int64  `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
}

type ItemList struct {
	Items []Item `json:"items"`
}

type Problem struct {
	Title  string  `json:"title"`
	Status int64   `json:"status"`
	Detail *string `json:"detail,omitempty"`
}
